#!/usr/bin/env bash

set -eu
current_dir=$(cd $(dirname $0) && pwd)

# OS情報を取得
source /etc/os-release
# VERSION_CODENAME=buster

# アップデートするリポジトリ
git_username="NSK-1010"
git_reponame="pi-app-manager-scripts-${VERSION_CODENAME}"

# バージョン情報の取得
version=$(curl -s https://api.github.com/repos/${git_username}/${git_reponame}/releases/latest | jq '.tag_name')
version=${version::-1}
version=${version:2}

# ダウンロードするURL
url="https://github.com/${git_username}/${git_reponame}.git"

# 展開先
extract_dir="${current_dir}/softwares"

# 一時保存先
download_path="/tmp/download/piappscripts"

# 設定した値の整形
extract_dir=${extract_dir%/}

# ディレクトリ作成
if [[ ! -d $extract_dir ]]; then
    mkdir -p $extract_dir
fi

# ダウンロード
git clone ${url} ${download_path}/

# 古いファイルを削除
rm -f $extract_dir/*

# 移動
mv ${download_path}/* $extract_dir
rm $extract_dir/README.md

# ダウンロードした一時ファイルを削除
rm -r $download_path

if [[ -z $(ls ${extract_dir} 2> /dev/null) ]]; then
    echo "Failed to update." >&2
    exit 1
else
    exit 0
fi
